"""Navigation events understood by the EZScore EFSM."""

OPEN_REPERTOIRE = "OPEN_REPERTOIRE"
OPEN_PLAYLISTS = "OPEN_PLAYLISTS"
OPEN_GROUPS = "OPEN_GROUPS"
OPEN_GROUP = "OPEN_GROUP"
OPEN_PLAYLIST = "OPEN_PLAYLIST"
OPEN_SONG = "OPEN_SONG"
BACK = "BACK"

ALL_EVENTS = frozenset({
    OPEN_REPERTOIRE, OPEN_PLAYLISTS, OPEN_GROUPS, OPEN_GROUP,
    OPEN_PLAYLIST, OPEN_SONG, BACK,
})
